In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.random.randn(100)

In [3]:
A

array([ 0.13367089,  1.36030639,  0.6851455 , -2.46643812, -0.07785062,
       -0.72150855, -0.09800638, -0.11945722, -0.39202455, -0.027912  ,
        0.07424125, -0.39703967,  0.09042771,  2.00317322,  0.29412772,
       -1.17196786, -0.99257182, -0.38468002, -0.06145063,  0.23589933,
        0.14167677,  0.49248962, -0.51722727,  0.37472851,  0.17091   ,
        1.47904428, -0.79561479, -0.54183322,  1.43034731, -0.24912532,
        2.64869378, -0.5287152 , -0.91479945, -0.59399968, -0.54103229,
        0.51171711, -1.19758868, -1.18065767,  0.22565476,  0.68421376,
        0.57436366,  0.04352527,  0.09442339,  0.04121631,  0.62313837,
       -1.40232928,  0.58066087, -0.68414491, -0.0268822 , -0.29505291,
        0.28786022, -0.54444356, -0.0163713 , -2.27942162,  0.95268213,
        0.52349463, -0.82421776, -0.42414169,  0.78331203, -0.1786959 ,
        1.39097134,  0.90909069,  3.14129392,  1.00000551, -1.11138403,
       -0.94051406,  1.14942568, -0.44640567, -1.53751175,  2.29

In [4]:
A = 10*A + 50

In [5]:
A

array([51.3367089 , 63.60306392, 56.85145505, 25.33561881, 49.2214938 ,
       42.78491448, 49.01993616, 48.80542781, 46.07975451, 49.72088003,
       50.74241252, 46.0296033 , 50.90427708, 70.03173223, 52.94127723,
       38.28032142, 40.07428184, 46.15319979, 49.38549368, 52.35899332,
       51.41676766, 54.92489616, 44.82772732, 53.74728509, 51.70909999,
       64.79044275, 42.04385214, 44.58166779, 64.30347312, 47.50874678,
       76.48693779, 44.71284798, 40.85200549, 44.06000323, 44.58967707,
       55.11717107, 38.02411319, 38.19342329, 52.25654758, 56.84213762,
       55.74363662, 50.43525267, 50.94423387, 50.41216306, 56.23138368,
       35.97670718, 55.80660869, 43.15855085, 49.73117797, 47.04947089,
       52.8786022 , 44.55556441, 49.83628705, 27.20578379, 59.5268213 ,
       55.23494634, 41.75782242, 45.75858311, 57.83312033, 48.21304104,
       63.90971343, 59.09090686, 81.4129392 , 60.00005508, 38.88615974,
       40.59485943, 61.49425682, 45.53594334, 34.6248825 , 72.98

In [6]:
A.shape

(100,)

array.shape 可以看array 的形狀

In [7]:
A.shape = (5, 20)

In [8]:
A

array([[51.3367089 , 63.60306392, 56.85145505, 25.33561881, 49.2214938 ,
        42.78491448, 49.01993616, 48.80542781, 46.07975451, 49.72088003,
        50.74241252, 46.0296033 , 50.90427708, 70.03173223, 52.94127723,
        38.28032142, 40.07428184, 46.15319979, 49.38549368, 52.35899332],
       [51.41676766, 54.92489616, 44.82772732, 53.74728509, 51.70909999,
        64.79044275, 42.04385214, 44.58166779, 64.30347312, 47.50874678,
        76.48693779, 44.71284798, 40.85200549, 44.06000323, 44.58967707,
        55.11717107, 38.02411319, 38.19342329, 52.25654758, 56.84213762],
       [55.74363662, 50.43525267, 50.94423387, 50.41216306, 56.23138368,
        35.97670718, 55.80660869, 43.15855085, 49.73117797, 47.04947089,
        52.8786022 , 44.55556441, 49.83628705, 27.20578379, 59.5268213 ,
        55.23494634, 41.75782242, 45.75858311, 57.83312033, 48.21304104],
       [63.90971343, 59.09090686, 81.4129392 , 60.00005508, 38.88615974,
        40.59485943, 61.49425682, 45.53594334, 3

    更改array 形狀的方法
    array.shape = (新的形狀)

In [9]:
A.reshape(100, 1)

array([[51.3367089 ],
       [63.60306392],
       [56.85145505],
       [25.33561881],
       [49.2214938 ],
       [42.78491448],
       [49.01993616],
       [48.80542781],
       [46.07975451],
       [49.72088003],
       [50.74241252],
       [46.0296033 ],
       [50.90427708],
       [70.03173223],
       [52.94127723],
       [38.28032142],
       [40.07428184],
       [46.15319979],
       [49.38549368],
       [52.35899332],
       [51.41676766],
       [54.92489616],
       [44.82772732],
       [53.74728509],
       [51.70909999],
       [64.79044275],
       [42.04385214],
       [44.58166779],
       [64.30347312],
       [47.50874678],
       [76.48693779],
       [44.71284798],
       [40.85200549],
       [44.06000323],
       [44.58967707],
       [55.11717107],
       [38.02411319],
       [38.19342329],
       [52.25654758],
       [56.84213762],
       [55.74363662],
       [50.43525267],
       [50.94423387],
       [50.41216306],
       [56.23138368],
       [35

    另外一個改變array 形狀的方法
    會另外產生一個array
    array.reshape(新的形狀)

In [10]:
A

array([[51.3367089 , 63.60306392, 56.85145505, 25.33561881, 49.2214938 ,
        42.78491448, 49.01993616, 48.80542781, 46.07975451, 49.72088003,
        50.74241252, 46.0296033 , 50.90427708, 70.03173223, 52.94127723,
        38.28032142, 40.07428184, 46.15319979, 49.38549368, 52.35899332],
       [51.41676766, 54.92489616, 44.82772732, 53.74728509, 51.70909999,
        64.79044275, 42.04385214, 44.58166779, 64.30347312, 47.50874678,
        76.48693779, 44.71284798, 40.85200549, 44.06000323, 44.58967707,
        55.11717107, 38.02411319, 38.19342329, 52.25654758, 56.84213762],
       [55.74363662, 50.43525267, 50.94423387, 50.41216306, 56.23138368,
        35.97670718, 55.80660869, 43.15855085, 49.73117797, 47.04947089,
        52.8786022 , 44.55556441, 49.83628705, 27.20578379, 59.5268213 ,
        55.23494634, 41.75782242, 45.75858311, 57.83312033, 48.21304104],
       [63.90971343, 59.09090686, 81.4129392 , 60.00005508, 38.88615974,
        40.59485943, 61.49425682, 45.53594334, 3

In [11]:
A = A.reshape(100, 1)

In [12]:
A

array([[51.3367089 ],
       [63.60306392],
       [56.85145505],
       [25.33561881],
       [49.2214938 ],
       [42.78491448],
       [49.01993616],
       [48.80542781],
       [46.07975451],
       [49.72088003],
       [50.74241252],
       [46.0296033 ],
       [50.90427708],
       [70.03173223],
       [52.94127723],
       [38.28032142],
       [40.07428184],
       [46.15319979],
       [49.38549368],
       [52.35899332],
       [51.41676766],
       [54.92489616],
       [44.82772732],
       [53.74728509],
       [51.70909999],
       [64.79044275],
       [42.04385214],
       [44.58166779],
       [64.30347312],
       [47.50874678],
       [76.48693779],
       [44.71284798],
       [40.85200549],
       [44.06000323],
       [44.58967707],
       [55.11717107],
       [38.02411319],
       [38.19342329],
       [52.25654758],
       [56.84213762],
       [55.74363662],
       [50.43525267],
       [50.94423387],
       [50.41216306],
       [56.23138368],
       [35